### ISSUE TITLE
Scores of the AI

### ISSUE THREAD

**Issue by zas97** [thomasahle/mcts-2048#1]
Hi !

I wondered how well this AI performed (mean scores, max tiles archived, etc...).

Thank you!

**Comment by thomasahle** [comment]
I believe the best I've had, with 1000 rollouts, is a 16K tile (represented as 14 in the interface).
4K tiles (represented as 12) are virtually always achieved.

If you have the computational resources to do a number of runs and gather statistics, I would be very happy to post them on the front page.

**Comment by zas97** [comment]
Thanks, I'm building a similar AI and I just wanted to have a benchmark.
